---
- name: Re-configure {{ vm_interface }} interface
  template:
    src: ifcfg-interface.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ vm_interface }}

- name: restart network service
  service: 
    name: network
    state: restarted
