---
- name: git clone contrail-kolla-ansible version contrail/ocata
  git:
    repo: 'https://github.com/Juniper/contrail-kolla-ansible.git'
    dest: /root/contrail-kolla-ansible
    version: contrail/ocata
    update: no

- name: git clone contrail-ansible-deployer
  git:
    repo: 'https://github.com/Juniper/contrail-ansible-deployer.git'
    dest: /root/contrail-ansible-deployer
    update: no

- name: populate contrail-kolla-ansible/etc/kolla/globals.yml
  template:
    src: etc_kolla_globals.j2
    dest: /root/contrail-kolla-ansible/etc/kolla/globals.yml

- name: populate contrail-ansible-deployer/inventory/hosts
  template:
    src: inventory_hosts.j2
    dest: /root/contrail-ansible-deployer/inventory/hosts

- name: populate contrail-ansible-deployer/inventory/group_vars/container_hosts.yml
  template:
    src: group_vars_container_hosts.j2
    dest: /root/contrail-ansible-deployer/inventory/group_vars/container_hosts.yml
