---
- name: Allow root SSH
  replace: 
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin yes'
    replace: 'PermitRootLogin yes'
    backup: yes

- name: Enable password authentication
  replace: 
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted

- name: git clone contrail-ansible-deployer
  git:
    repo: 'https://github.com/Juniper/contrail-ansible-deployer.git'
    dest: /root/contrail-ansible-deployer
    update: no

- name: populate contrail-ansible-deployer/config/instances.yaml
  template:
    src: config_instances.j2
    dest: /root/contrail-ansible-deployer/config/instances.yaml
