---
- name: Install epel-release
  yum: 
    name: epel-release
    state: latest

- name: Install ansible-2.4.2.0
  yum: 
    name: ansible-2.4.2.0
    state: present

- name: Install git
  yum: 
    name: git
    state: latest
