- name: Re-configure eno1 interface
  template:
    src: ifcfg-eno1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eno1

- name: Re-configure /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: restart network service
  service: 
    name: network
    state: restarted
