---
- name: Allow root SSH
  replace: 
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin yes'
    replace: 'PermitRootLogin yes'
    backup: yes

- name: Enable password authentication
  replace: 
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted

- name: git clone contrail-dev-env
  git:
    repo: 'https://github.com/Juniper/contrail-dev-env.git'
    dest: /root/contrail-dev-env
    update: no

- name: Increase docker base size to 200G
  replace: 
    path: /root/contrail-dev-env/startup.sh
    regexp: 'dm\.basesize=20G'
    replace: 'dm.basesize=200G'
    backup: yes

- name: run startup.sh to install dev containers
  shell: cd /root/contrail-dev-env && ./startup.sh -b && ./vm-dev-env/init.sh

- name: auto start docker.server at boot
  systemd: name=docker enabled=yes

#- name: copy the script to start build
#  copy:
#    src: scons_build.sh
#    dest: /tmp/scons_build.sh
#
#- name: copy the script to start build
#  file:
#    path: /tmp/scons_build.sh
#    mode: 755
#
#- name: setup dev container
#  shell: script=$(cat /tmp/scons_build.sh) && docker exec contrail-developer-sandbox bash -l -c "$script" > /tmp/scons.log
