---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install ansible-2.3.1.0
  yum: 
    name: ansible-2.3.1.0
    state: present

- name: Install git
  yum: 
    name: git
    state: latest

- name: Install net-tools
  yum: 
    name: net-tools
    state: latest

- name: Install wget
  yum: 
    name: wget
    state: latest

- name: Install python-pip
  yum: 
    name: python-pip
    state: latest

- name: Install tmux
  yum: 
    name: tmux
    state: latest

- name: Install tree
  yum: 
    name: tree
    state: latest

- name: Install vim
  yum: 
    name: vim
    state: latest

- name: Upgrade pip
  pip: 
    name: pip
    state: latest

- name: Update tmux config
  template:
    src: tmux.conf.j2
    dest: /root/.tmux.conf

- name: Install gnome desktop
  command: yum -y groupinstall "GNOME Desktop"

- command: ln -sf /lib/systemd/system/runlevel5.target /etc/systemd/system/graphical.target

#- name: Reboot server
#  command: /sbin/shutdown -r +1
#  async: 0
#  poll: 0
#  ignore_errors: true
#
#- name: sleep for 65 seconds and continue with play
#  wait_for: timeout=65
#  delegate_to: localhost
#
#- name: Wait for the server to finish rebooting
#  local_action: wait_for host="{{ ansible_host }}" search_regex=OpenSSH port=22 timeout=600
