global_configuration:
  CONTAINER_REGISTRY: ci-repo.englab.juniper.net:5000
  REGISTRY_PRIVATE_INSECURE: True
provider_config:
  bms:
    ssh_user: root
    ssh_pwd: c0ntrail123
    ntpserver: ntp.juniper.net
    domainsuffix: local
instances:
  ha-node1:
    ip: 10.155.75.131
    provider: bms
    roles:
      config:
      config_database:
      control:
      webui:
      analytics:
      analytics_database:
      vrouter:
      openstack:
      openstack_compute:
  ha-node2:
    ip: 10.155.75.132
    provider: bms
    roles:
      config:
      config_database:
      analytics:
      analytics_database:
  ha-node3:
    ip: 10.155.75.133
    provider: bms
    roles:
      config:
      config_database:
      analytics:
      analytics_database:
contrail_configuration:
  CONTRAIL_VERSION: 5.0-302
  CLOUD_ORCHESTRATOR: openstack
  RABBITMQ_NODE_PORT: 5673
  ENCAP_PRIORITY: VXLAN,MPLSoUDP,MPLSoGRE
  OPENSTACK_VERSION: ocata
  AUTH_MODE: keystone
  KEYSTONE_AUTH_URL_VERSION: /v3
kolla_config:
  kolla_globals:
    enable_haproxy: no
  kolla_passwords:
    keystone_admin_password: contrail123
