---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install ansible
  yum: 
    name: ansible
    state: latest

- name: Install git
  yum: 
    name: git
    state: latest
