---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install ansible
  yum:
    name: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.4.6.0-1.el7.ans.noarch.rpm
    state: latest

- name: Install git
  yum:
    name: git
    state: latest

- name: Install tmux
  yum:
    name: tmux
    state: latest

- name: Disable firewall
  service:
    name: firewalld
    enabled: no
    state: stopped
