---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install ansible-2.4.3.0
  yum: 
    name: http://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.4.3.0-1.el7.ans.noarch.rpm
    state: present

- name: Install git
  yum: 
    name: git
    state: latest
