---
- name: Provision headless dev vm
  hosts: all
  gather_facts: no
  become: True
  roles:
    - network
    - setup_root
    - base_pkgs
    - dev_pkgs
    - tmux
    - devenv
  vars:
    set_root_pass: 'mpls'
