global_configuration:
  CONTAINER_REGISTRY: ci-repo.englab.juniper.net:5000
  REGISTRY_PRIVATE_INSECURE: True
provider_config:
  bms:
    ssh_user: root
    ssh_pwd: c0ntrail123
    ntpserver: ntp.juniper.net
    domainsuffix: local
instances:
  aio:
    ip: 192.168.10.10
    provider: bms
    roles:
      dhcp:
      config:
      config_database:
      control:
      webui:
      analytics:
      analytics_database:
      vrouter:
      openstack_control:
      openstack_network:
      openstack_storage:
      openstack_monitoring:
      openstack_compute:
contrail_configuration:
  CONTRAIL_VERSION: 5.0-272
  CLOUD_ORCHESTRATOR: openstack
  RABBITMQ_NODE_PORT: 5673
  ENCAP_PRIORITY: VXLAN,MPLSoUDP,MPLSoGRE
  OPENSTACK_VERSION: queens
  AUTH_MODE: keystone
  KEYSTONE_AUTH_URL_VERSION: /v3
  GENERATE_SSH: True
  USE_OPENSTACK_TFTP: True
kolla_config:
  kolla_globals:
    enable_haproxy: no
  kolla_passwords:
    keystone_admin_password: contrail123
